'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class AirlineTaxonomy
        Public Property Code As String
        Public Property AnyParentCode As String
        Public Property Title As String
        Public Property Description As String
    
        Public Overridable Property AirlineFeatures As ICollection(Of AirlineFeature) = New HashSet(Of AirlineFeature)
    
    End Class

End Namespace
