'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class AirlineFeature
        Public Property Code As String
        Public Property AirlineTaxonomyCode As String
        Public Property Type As String
        Public Property Vale As String
    
        Public Overridable Property AirlineTaxonomy As AirlineTaxonomy
    
    End Class

End Namespace
