'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class Ancillary
        Public Property Code As String
        Public Property ProductCatalogueCode As String
        Public Property Name As String
        Public Property Description As String
    
        Public Overridable Property ProductCatalogue As ProductCatalogue
        Public Overridable Property ProductToAncillaries As ICollection(Of ProductToAncillary) = New HashSet(Of ProductToAncillary)
    
    End Class

End Namespace
