'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class MinConnectTimeAcceptanceRule
        Public Property Code As String
        Public Property ProductCatalogueCode As String
        Public Property TransportDesignator As String
        Public Property AccountingCode As String
        Public Property LocationCode As String
        Public Property Onward As Nullable(Of Boolean)
        Public Property Min As Nullable(Of System.TimeSpan)
        Public Property Max As Nullable(Of System.TimeSpan)
        Public Property Accepted As Nullable(Of Boolean)
    
        Public Overridable Property ProductCatalogue As ProductCatalogue
    
    End Class

End Namespace
