'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Airline

    Partial Public Class AirlineEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=AirlineEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property AirlineFeatures() As DbSet(Of AirlineFeature)
        Public Overridable Property AirlineTaxonomies() As DbSet(Of AirlineTaxonomy)
        Public Overridable Property Ancillaries() As DbSet(Of Ancillary)
        Public Overridable Property CancelRestrictions() As DbSet(Of CancelRestriction)
        Public Overridable Property CarrierAcceptanceRules() As DbSet(Of CarrierAcceptanceRule)
        Public Overridable Property ChangeRestrictions() As DbSet(Of ChangeRestriction)
        Public Overridable Property Markets() As DbSet(Of Market)
        Public Overridable Property MinConnectTimeAcceptanceRules() As DbSet(Of MinConnectTimeAcceptanceRule)
        Public Overridable Property OperatingLegs() As DbSet(Of OperatingLeg)
        Public Overridable Property Products() As DbSet(Of Product)
        Public Overridable Property ProductCatalogues() As DbSet(Of ProductCatalogue)
        Public Overridable Property ProductToAncillaries() As DbSet(Of ProductToAncillary)
        Public Overridable Property Resources() As DbSet(Of Resource)
        Public Overridable Property Routes() As DbSet(Of Route)
        Public Overridable Property SeatAttributes() As DbSet(Of SeatAttribute)
        Public Overridable Property SeatMaps() As DbSet(Of SeatMap)
        Public Overridable Property Settlements() As DbSet(Of Settlement)
        Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
        Public Overridable Property TransportVehicles() As DbSet(Of TransportVehicle)
        Public Overridable Property TransportVehicleToProducts() As DbSet(Of TransportVehicleToProduct)
        Public Overridable Property Airlines() As DbSet(Of Airline)
    
    End Class

End Namespace
