'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class OperatingLeg
        Public Property Code As String
        Public Property RouteCode As String
        Public Property TransportVehicle As String
        Public Property DepartureTime As String
        Public Property DepartureDay As String
        Public Property ServiceStart As String
        Public Property ServiceEnd As String
    
        Public Overridable Property Route As Route
    
    End Class

End Namespace
