'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class Product
        Public Property Code As String
        Public Property Name As String
        Public Property Description As String
    
        Public Overridable Property CancelRestrictions As ICollection(Of CancelRestriction) = New HashSet(Of CancelRestriction)
        Public Overridable Property ChangeRestrictions As ICollection(Of ChangeRestriction) = New HashSet(Of ChangeRestriction)
        Public Overridable Property ProductToAncillaries As ICollection(Of ProductToAncillary) = New HashSet(Of ProductToAncillary)
        Public Overridable Property TransportVehicleToProducts As ICollection(Of TransportVehicleToProduct) = New HashSet(Of TransportVehicleToProduct)
    
    End Class

End Namespace
