'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class ProductToAncillary
        Public Property AncillaryCode As String
        Public Property ProductCode As String
        Public Property [Optional] As Nullable(Of Boolean)
    
        Public Overridable Property Ancillary As Ancillary
        Public Overridable Property Product As Product
    
    End Class

End Namespace
