'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class ProductCatalogue
        Public Property Code As String
        Public Property TransportDesignator As String
        Public Property AccountingCode As String
        Public Property Type As String
        Public Property AirlineCode As Single
    
        Public Overridable Property Ancillaries As ICollection(Of Ancillary) = New HashSet(Of Ancillary)
        Public Overridable Property CarrierAcceptanceRules As ICollection(Of CarrierAcceptanceRule) = New HashSet(Of CarrierAcceptanceRule)
        Public Overridable Property Markets As ICollection(Of Market) = New HashSet(Of Market)
        Public Overridable Property MinConnectTimeAcceptanceRules As ICollection(Of MinConnectTimeAcceptanceRule) = New HashSet(Of MinConnectTimeAcceptanceRule)
        Public Overridable Property Settlements As ICollection(Of Settlement) = New HashSet(Of Settlement)
        Public Overridable Property TransportVehicles As ICollection(Of TransportVehicle) = New HashSet(Of TransportVehicle)
        Public Overridable Property Airline As Airline
    
    End Class

End Namespace
