'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class Route
        Public Property Code As String
        Public Property MarketCode As String
        Public Property DepartureLocation As String
        Public Property ArrivalLocation As String
    
        Public Overridable Property Market As Market
        Public Overridable Property OperatingLegs As ICollection(Of OperatingLeg) = New HashSet(Of OperatingLeg)
    
    End Class

End Namespace
