'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class SeatAttribute
        Public Property Code As String
        Public Property SeatMap As String
        Public Property Row As String
        Public Property Column As String
        Public Property Attributes As String
    
        Public Overridable Property SeatMapCode As SeatMap
    
    End Class

End Namespace
