'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class SeatMap
        Public Property Code As String
        Public Property TransportVehicleCode As String
        Public Property ProductCode As String
        Public Property Floor As String
        Public Property StartRow As String
        Public Property EndRow As String
        Public Property Columns As String
        Public Property Attributes As String
    
        Public Overridable Property SeatAttributes As ICollection(Of SeatAttribute) = New HashSet(Of SeatAttribute)
        Public Overridable Property TransportVehicleToProduct As TransportVehicleToProduct
    
    End Class

End Namespace
