'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Airline

    Partial Public Class TransportVehicleToProduct
        Public Property TransportVehicleCode As String
        Public Property ProductCode As String
    
        Public Overridable Property Product As Product
        Public Overridable Property SeatMaps As ICollection(Of SeatMap) = New HashSet(Of SeatMap)
        Public Overridable Property TransportVehicle As TransportVehicle
    
    End Class

End Namespace
